name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: 'ivy_check'
